FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o pr-reviewer ./main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

COPY --from=builder /app/pr-reviewer .
COPY --from=builder /app/configs/prod.yml ./config.yaml

EXPOSE 8080

CMD ["./pr-reviewer", "-config", "config.yaml"]

